@baseUrl = http://localhost:5000


################################################## Property
GET {{baseUrl}}/Property
#####
POST {{baseUrl}}/Property?amount=1
Content-type: application/json

"xxx"
#####
